### ISSUE TITLE
Cannot retrieve data of whether a field is located within a table or not

### ISSUE THREAD

**Issue by niki-cy** [kintone/config-helper#10]
Unlike using the GET Form Fields API, https://developer.kintone.io/hc/en-us/articles/115005509288, config-helper does not respond information of the fields that are within a table. It is possible to retrieve the data of the fields that are inside of a table, but not the fact that they are located within a specific table. I ran into this problem when fixing a plug-in to use config-helper instead of the GET Form Fields API, where ideally I would like to only show Number fields that are located inside of a Table. Using config-helper as it is, there is no way to differentiate whether a Number field is located inside of a table, or just in the form as an individual field. Please let me know if I can explain this any better. Thank you!

**Comment by potaracom** [comment]
Do you have any plans to this issue.

**Comment by koba04** [comment]
That seems to be a reasonable request. I'll consider supporting this. Thank you!
