### ISSUE TITLE
The information of the lookup field in the sub table can be acquired.

### ISSUE THREAD

**Issue by Naoto00** [kintone/config-helper#3]
Although the limitation that "lookup field can not be acquired" is stated, 
if you actually try to get it you can get it.

https://github.com/kintone/config-helper#limitations

**Comment by koba04** [comment]
@Naoto00 Would you confirm that the issue has been fixed by the following file?

https://github.com/toshi-toma/config-helper/blob/fix-exclude-lookup-field/dist/kintone-config-helper.js

**Comment by Naoto00** [comment]
@koba04 @toshi-toma
I confirmed.
Thanks!
